name: clickbyme
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #curved 네비게이션바를 만들기 위함
  curved_navigation_bar: ^1.0.2
  intl: ^0.17.0
  #애니메이션효과를 주기 위함
  animated_text_kit: ^4.2.1
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.5
  transition: ^2.0.2
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  #firebase 기능
  cloud_firestore: ^3.1.15
  firebase_auth: ^3.3.6
  firebase_messaging: ^11.4.0
  flutter_local_notifications: any
  google_sign_in: ^5.3.1
  firebase_core: ^1.12.0
  flutter_secure_storage: ^5.0.2
  #카카오 sdk
  kakao_flutter_sdk: ^1.2.1
  dio: ^4.0.0
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.5
  platform: ^3.0.0
  package_info_plus: ^1.0.4
  package_info: ^2.0.0
  #get이나 provider를 추후 사용시 대비
  get_it: ^1.0.3+2
  provider: ^6.0.2
  get: ^4.6.5
  #image picker
  image_picker: ^0.8.4
  multi_image_picker2: ^5.0.2
  dotted_border: ^2.0.0
  #permission 허용여부 묻기
  permission_handler: ^9.2.0
  flutter_email_sender: any
  #sticky상태로 헤더에 붙게 하기 위함
  #UI
  #calendar_view: ^0.0.4
  #syncfusion_flutter_calendar: ^20.1.55
  flutter_neumorphic: ^3.0.3
  #timeline_tile: ^2.0.0
  #calendar_timeline: ^1.0.4
  flutter_switch: ^0.3.2
  shimmer: ^2.0.0
  flutter_speed_dial: ^5.1.0
  table_calendar: ^3.0.3
  #sticky_headers: ^0.3.0+2
  textfield_tags: ^2.0.0+1
  google_fonts: ^3.0.1
  text_scroll: ^0.1.0
  avoid_keyboard: ^0.3.0
  
  another_flushbar: ^1.10.29
  alphabet_scroll_view: ^0.3.1
  detectable_text_field : ^2.0.3
  flutter_app_badger: ^1.4.0
  focused_menu: ^1.0.5
  flutter_colorpicker: ^1.0.3
  #local db
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  hive_listener: ^1.2.1
  #contacts_service: ^0.6.3
  local_auth: ^2.1.2
  local_auth_ios: ^1.0.9
  local_auth_android: ^1.0.11
  device_info: ^2.0.3
  ios_utsname_ext: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/instagram.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
